name:                esqueleto-experimental-example
version:             0.1.0.0
github:              "belevy/esqueleto-experimental-example"
license:             BSD3
author:              "Ben Levy"
maintainer:          "benjaminlevy007@gmail.com"
copyright:           "2019 Benjamin Levy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/belevy/esqueleto-experimental-example#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
    - esqueleto
    - persistent
    - persistent-sqlite
    - persistent-template
    - time
    - text

executables:
  example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esqueleto-experimental-example 

tests:
  example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esqueleto-experimental-example 
